spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social-app?useSSl=false&serverTimezone=UTC
    username: hbstudent
    password: hbstudent

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false




